In [1]:
# 

import numpy as np

In [2]:
# データをファイルから読み込み．
test=np.loadtxt("./water_10.0/bec2.txt")
print(test)

#そのうち，対角成分合計3*3=9個を取り出す．
print(test[0][0])

[[ 3.4017e-01  6.3170e-02  0.0000e+00]
 [ 6.7450e-02 -5.8144e-01  0.0000e+00]
 [-1.0000e-05 -0.0000e+00 -5.9689e-01]
 [-1.7098e-01 -2.2630e-01  0.0000e+00]
 [-2.8600e-03  2.1768e-01  0.0000e+00]
 [-0.0000e+00 -0.0000e+00  2.3625e-01]
 [-1.9363e-01  1.6257e-01  0.0000e+00]
 [-6.6060e-02  2.4179e-01  0.0000e+00]
 [-0.0000e+00  0.0000e+00  2.3635e-01]]
0.34017


In [3]:
# OとH1，H2を保存するndarrayを作成する．各18*(3+1)成分必要
O=np.ones((18,4))
print(O)
O[0][1]=2.0
print(O)
H1=np.ones((18,4))
H2=np.ones((18,4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 2. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
# 10-180までのリスト
deg=np.linspace(10,180,18)
print(deg)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100. 110. 120. 130. 140.
 150. 160. 170. 180.]


In [5]:
# 各ファイルからデータを読み込む．

#カウンタ
i=0

for angle in deg:
    #ファイル名
    file="./water_{}/bec2.txt".format(str(angle))
    print(file)
    
    #ファイル読み込み
    data=np.loadtxt(file)
    
    #データ抽出
    O[i][0]=angle
    O[i][1]=data[0][0] #Oxx
    O[i][2]=data[1][1] #Oyy
    O[i][3]=data[2][2] #Ozz

    H1[i][0]=angle
    H1[i][1]=data[3][0] #H1xx
    H1[i][2]=data[4][1] #H1yy
    H1[i][3]=data[5][2] #H1zz

    H2[i][0]=angle    
    H2[i][1]=data[6][0] #H2xx
    H2[i][2]=data[7][1] #H2yy
    H2[i][3]=data[8][2] #H2zz
    
    #カウンタ更新
    i+=1


./water_10.0/bec2.txt
./water_20.0/bec2.txt
./water_30.0/bec2.txt
./water_40.0/bec2.txt
./water_50.0/bec2.txt
./water_60.0/bec2.txt
./water_70.0/bec2.txt
./water_80.0/bec2.txt
./water_90.0/bec2.txt
./water_100.0/bec2.txt
./water_110.0/bec2.txt
./water_120.0/bec2.txt
./water_130.0/bec2.txt
./water_140.0/bec2.txt
./water_150.0/bec2.txt
./water_160.0/bec2.txt
./water_170.0/bec2.txt
./water_180.0/bec2.txt


In [6]:
print(H2)

[[ 1.0000e+01 -1.9363e-01  2.4179e-01  2.3635e-01]
 [ 2.0000e+01 -1.2712e-01  2.4417e-01  2.5652e-01]
 [ 3.0000e+01 -1.8110e-02  2.0099e-01  2.7408e-01]
 [ 4.0000e+01  9.0770e-02  1.3787e-01  2.8525e-01]
 [ 5.0000e+01  1.7116e-01  8.4670e-02  2.9160e-01]
 [ 6.0000e+01  2.1949e-01  5.3730e-02  2.9585e-01]
 [ 7.0000e+01  2.4590e-01  4.2010e-02  3.0023e-01]
 [ 8.0000e+01  2.6199e-01  4.2950e-02  3.0573e-01]
 [ 9.0000e+01  2.7573e-01  5.1440e-02  3.1297e-01]
 [ 1.0000e+02  2.9213e-01  6.6350e-02  3.2191e-01]
 [ 1.1000e+02  3.1393e-01  8.9280e-02  3.3245e-01]
 [ 1.2000e+02  3.4232e-01  1.2299e-01  3.4438e-01]
 [ 1.3000e+02  3.7746e-01  1.6801e-01  3.5709e-01]
 [ 1.4000e+02  4.1715e-01  2.2375e-01  3.6999e-01]
 [ 1.5000e+02  4.5679e-01  2.8555e-01  3.8228e-01]
 [ 1.6000e+02  4.9017e-01  3.4390e-01  3.9272e-01]
 [ 1.7000e+02  5.1045e-01  3.8664e-01  3.9991e-01]
 [ 1.8000e+02  5.1741e-01  4.0259e-01  4.0259e-01]]


In [7]:
# データを書き出し． 
# O_bec.txtなど3つのファイルにangle xx yy zzの形式で入れる．

# Oのファイル
np.savetxt('O_bec.txt', O, header='# angle Zxx Zyy Zzz') 

# H1のファイル
np.savetxt('H1_bec.txt', H1, header='# angle Zxx Zyy Zzz') 

# H2のファイル
np.savetxt('H2_bec.txt', H2, header='# angle Zxx Zyy Zzz') 


In [24]:
r=0.9693
g=104.107
g=100
print(r*np.cos(g/180*np.pi))
print(r*np.sin(g/180*np.pi))

-0.16831717861255555
0.9545741549947333


In [6]:
# 有効電荷の総和則を満たしているかの確認

#カウンタ
i=0

for angle in deg:
    #ファイル名
    file="./water_{}/bec2.txt".format(str(angle))
    print(file)
    
    #ファイル読み込み
    data=np.loadtxt(file)
    
    ##データ抽出
    print(data[0][0]+data[3][0]+data[6][0])#xxの総和
    print(data[1][1]+data[4][1]+data[7][1])#yyの総和
    print(data[2][2]+data[5][2]+data[8][2])#zzの総和
    
Ab initio molecular dynamics study of temperature and pressure-dependent infrared dielectric functions of liquid methanolAb initio molecular dynamics study of temperature and pressure-dependent infrared dielectric functions of liquid methanol    #カウンタ更新
    i+=1



./water_10.0/bec2.txt
-0.024440000000000017
-0.12196999999999997
-0.12429000000000007
./water_20.0/bec2.txt
-0.035120000000000026
-0.12015999999999999
-0.13226
./water_30.0/bec2.txt
-0.05105
-0.11399999999999999
-0.14007000000000003
./water_40.0/bec2.txt
-0.06857
-0.10418
-0.14709
./water_50.0/bec2.txt
-0.08267
-0.09557999999999997
-0.15292999999999995
./water_60.0/bec2.txt
-0.09168000000000001
-0.09081
-0.15761999999999998
./water_70.0/bec2.txt
-0.09682999999999997
-0.08990999999999999
-0.16075
./water_80.0/bec2.txt
-0.09917999999999999
-0.09352999999999999
-0.16392
./water_90.0/bec2.txt
-0.09948000000000001
-0.09948
-0.16616999999999993
./water_100.0/bec2.txt
-0.09839999999999999
-0.109
-0.16903000000000007
./water_110.0/bec2.txt
-0.09449999999999997
-0.11961999999999998
-0.17140999999999995
./water_120.0/bec2.txt
-0.0859299999999999
-0.12889
-0.17247
./water_130.0/bec2.txt
-0.07588000000000006
-0.13984000000000002
-0.17442999999999997
./water_140.0/bec2.txt
-0.06630999999999998
-0.1