In [1]:
# 水の分極（双極子モーメント）の計算

In [2]:
import numpy as np

In [23]:
# WCと3つの原子座標からpolarization_vectorを返す関数
def polarization_WF(WF1,WF2,WF3,WF4,O,H1,H2):
    # 双極子モーメントベクトルの計算
    polarization=-2*(WF1+WF2+WF3+WF4)+6*O+(H1+H2)
    #print("polarization vector =", polarization)
    return polarization

# BECと3つの原始座標からpolarization_vectorを返す関数
def polarization_BEC(ZO,ZH1,ZH2,O,H1,H2):
    # ASR 
    meanZ=(ZO+ZH1+ZH2)/3.0
    newZO=ZO-meanZ
    newZH1=ZH1-meanZ
    newZH2=ZH2-meanZ
    #体積．celldmはbohrだからAに変換している．
    V=10*3

    #単位に注意．分極の単位はC/m2である．
    #分極はは「単位体積当たりの双極子モーメントとして定義される。」
    #したがって，双極子モーメントの単位がC*mであることと辻褄があう．
    
    #したがって，Pの計算でVで割る必要は（上の計算と合わせるだけなら）ない！
    # 分極の計算．かける順番に注意．
    P=np.dot(newZO,O)+np.dot(newZH1,H1)+np.dot(newZH2,H2)
    return P
    
# ASR
def ASR_BEC(ZO,ZH1,ZH2):
    # ASR 
    meanZ=(ZO+ZH1+ZH2)/3.0
    newZO=ZO-meanZ
    newZH1=ZH1-meanZ
    newZH2=ZH2-meanZ
    return [newZO, newZH1, newZH2]

In [2]:
# 水分子の情報
#O 0.00 0.00 0.00
#H 0.9693 0.00 0.00
#H -0.23625088367 0.94006808794 0.00

# 単位はいずれもAngstrom．
# Oに+6，Hに+1，4つのWFには-2を割り当てる．

In [49]:
#各原子の座標(単位はAngstrom)
O=np.array([0.00,0.00,0.00])
H1=np.array([0.9693,0.00,0.00])
H2=np.array([-0.2362508836,0.94006808794,0.00])

In [38]:
#WCの座標（単位はAngstrom）
WF1=np.array([-0.107125,  0.514973, -0.000000])
WF2=np.array([0.526914,  0.017817, -0.000000 ])
WF3=np.array([-0.085620, -0.110962, -0.276969])
WF4=np.array([-0.085619, -0.110961,  0.276970 ])

In [39]:
# 完全にイオン性の場合，Hに+1，Oに-2を割り当てればよさそう．
p_test=-2*O+(H1+H2)
d_test=np.linalg.norm(p_test)*4.79990626955
print("polarization vector =", p_test)
print("dipole moment = ", d_test, "  [D]" )

polarization vector = [0.73304912 0.94006809 0.        ]
dipole moment =  5.72194130091999   [D]


In [42]:
# MDで使われる古典電荷の割り当ては，Oに0.8，Hに0.4くらい．
p_test=-0.8*O+0.4*(H1+H2)
d_test=np.linalg.norm(p_test)*4.79990626955
print("polarization vector =", p_test)
print("dipole moment = ", d_test, "  [D]" )

polarization vector = [0.29321965 0.37602724 0.        ]
dipole moment =  2.288776520367996   [D]


In [43]:
# 双極子モーメントベクトルの計算
polarization=-2*(WF1+WF2+WF3+WF4)+6*O+(H1+H2)
print("polarization vector =", polarization)

# 双極子モーメントの大きさの計算．現在の単位はAngstrom*1(e)となっている．
# 単位を合わせる．（単位がデバイになる．）
dipole=np.linalg.norm(polarization)*4.79990626955
print("dipole moment = ", dipole, "  [D]" )


polarization vector = [ 2.35949116e-01  3.18334088e-01 -2.00000000e-06]
dipole moment =  1.9019296356639406   [D]


# 以下BECから計算する方法．

# もっとシステマチックに，BECファイルを取得して計算するやり方1．


In [45]:
# 有効電荷の取得
ZO=np.loadtxt("bec_O_1.txt")
ZH1=np.loadtxt("bec_H1_1.txt")
ZH2=np.loadtxt("bec_H2_1.txt")

print(ZO)
print(ZH1)
print(ZH2)

[[-3.9515e-01  9.1930e-02 -0.0000e+00]
 [ 9.2560e-02 -3.5153e-01  0.0000e+00]
 [ 1.0000e-05  2.0000e-05 -6.5100e-01]]
[[ 9.4860e-02 -8.1700e-02  0.0000e+00]
 [-5.1740e-02  2.7679e-01 -0.0000e+00]
 [-1.0000e-05 -1.0000e-05  3.2504e-01]]
[[ 3.0029e-01 -1.0240e-02 -0.0000e+00]
 [-4.0820e-02  7.4740e-02  0.0000e+00]
 [-1.0000e-05 -1.0000e-05  3.2596e-01]]


In [46]:
# 分極の計算．かける順番に注意．
P=np.dot(ZO,O)+np.dot(ZH1,H1)+np.dot(ZH2,H2)
print(P)

# 双極子モーメントの大きさの計算．（現在の単位はAngstrom*）
# 単位を合わせる．1.34410958が係数．（単位がデバイになる．）
D=np.linalg.norm(P)*4.79990626955
print("dipole moment = ", D , "  [D]" )

[ 1.13777229e-02  2.97528680e-02 -1.67311720e-05]
dipole moment =  0.1528968694266839   [D]


#  もっとシステマチックに，ASRを含めて，上で定義した関数を使う．


In [83]:
# 有効電荷の取得
ZO=np.loadtxt("bec_new_O_dFdE.txt")
ZH1=np.loadtxt("bec_new_H1_dFdE.txt")
ZH2=np.loadtxt("bec_new_H2_dFdE.txt")

print("#######")
z=ASR_BEC(ZO,ZH1,ZH2)
print(z[0])
print("#######")
print(z[1])
print("#######")
print(z[2])


P=polarization_BEC(ZO,ZH1,ZH2,O,H1,H2)
print(P)

# 双極子モーメントの大きさの計算．（現在の単位はAngstrom*）
# 単位を合わせる．1.34410958が係数．（単位がデバイになる．）
D=np.linalg.norm(P)*4.79990626955
print("dipole moment = ", D , "  [D]" )

#######
[[-0.46300667  0.07527     0.        ]
 [ 0.07596    -0.42357     0.        ]
 [ 0.          0.         -0.67730667]]
#######
[[ 0.16457333 -0.04834    -0.        ]
 [-0.06426     0.27697     0.        ]
 [ 0.          0.          0.33842333]]
#######
[[ 0.29843333 -0.02693     0.        ]
 [-0.0117      0.1466     -0.        ]
 [-0.          0.          0.33888333]]
[0.08358279 0.07962266 0.        ]
dipole moment =  0.5540899196136148   [D]


# 水の角度が変わった時のデータから双極子モーメントの変化を計算する．

In [23]:
# 有効電荷の取得 80度
ZO=np.loadtxt("./change/bec_O_80.txt")
ZH1=np.loadtxt("./change/bec_H1_80.txt")
ZH2=np.loadtxt("./change/bec_H2_80.txt")

# ASR 
meanZ=(ZO+ZH1+ZH2)/3.0
newZO=ZO-meanZ
newZH1=ZH1-meanZ
newZH2=ZH2-meanZ
print(newZO)
print(newZH1)
print(newZH2)

# 有効電荷の取得 90度
ZO=np.loadtxt("./change/bec_O_90.txt")
ZH1=np.loadtxt("./change/bec_H1_90.txt")
ZH2=np.loadtxt("./change/bec_H2_90.txt")

# ASR 
meanZ=(ZO+ZH1+ZH2)/3.0
anewZO=ZO-meanZ
anewZH1=ZH1-meanZ
anewZH2=ZH2-meanZ
print(anewZO)
print(anewZH1)
print(anewZH2)

# 有効電荷の取得 100度
ZO=np.loadtxt("./change/bec_O_100.txt")
ZH1=np.loadtxt("./change/bec_H1_100.txt")
ZH2=np.loadtxt("./change/bec_H2_100.txt")

# ASR 
meanZ=(ZO+ZH1+ZH2)/3.0
bnewZO=ZO-meanZ
bnewZH1=ZH1-meanZ
bnewZH2=ZH2-meanZ
print(bnewZO)
print(bnewZH1)
print(bnewZH2)

[[-3.55890000e-01  9.19400000e-02  0.00000000e+00]
 [ 8.82266667e-02 -3.82583333e-01  0.00000000e+00]
 [ 3.33333333e-06  3.33333333e-06 -7.21120000e-01]]
[[ 6.08400000e-02 -5.04200000e-02  0.00000000e+00]
 [-4.23333333e-03  3.08456667e-01  0.00000000e+00]
 [ 3.33333333e-06 -6.66666667e-06  3.60750000e-01]]
[[ 2.95050000e-01 -4.15200000e-02  0.00000000e+00]
 [-8.39933333e-02  7.41266667e-02  0.00000000e+00]
 [-6.66666667e-06  3.33333333e-06  3.60370000e-01]]
[[-3.93490000e-01  9.00433333e-02 -0.00000000e+00]
 [ 9.00433333e-02 -3.93490000e-01 -0.00000000e+00]
 [ 3.33333333e-06  3.33333333e-06 -7.36720000e-01]]
[[ 8.46000000e-02 -5.29766667e-02  0.00000000e+00]
 [-3.70666667e-02  3.08890000e-01  0.00000000e+00]
 [ 3.33333333e-06 -6.66666667e-06  3.68360000e-01]]
[[ 3.08890000e-01 -3.70666667e-02  0.00000000e+00]
 [-5.29766667e-02  8.46000000e-02  0.00000000e+00]
 [-6.66666667e-06  3.33333333e-06  3.68360000e-01]]
[[-4.38270000e-01  9.05333333e-02  0.00000000e+00]
 [ 9.20166667e-02 -4.1496

In [65]:
# 3つの座標の計算．
distance=0.9693
x_array=distance*np.array([np.cos(80*np.pi/180),np.cos(90*np.pi/180),np.cos(100*np.pi/180)])
y_array=distance*np.array([np.sin(80*np.pi/180),np.sin(90*np.pi/180),np.sin(100*np.pi/180)])
z_array=np.zeros(3)

In [64]:
delP=np.dot(newZH2,[x_array[1]-x_array[0],y_array[1]-y_array[0],0])+np.dot(anewZH2,[x_array[2]-x_array[1],y_array[2]-y_array[1],0])
delP2=np.dot(anewZH2,[x_array[1]-x_array[0],y_array[1]-y_array[0],0])+np.dot(bnewZH2,[x_array[2]-x_array[1],y_array[2]-y_array[1],0])
print(delP)
print(delP2)

NameError: name 'anewZH2' is not defined

In [68]:
# water_80
#WCの座標（単位はAngstrom）
WF1=np.array([-0.094697, -0.078645,  0.285048])
WF2=np.array([0.522090, -0.030953, -0.000002 ])
WF3=np.array([0.056493,  0.520710, -0.000002])
WF4=np.array([-0.094701, -0.078649, -0.285043 ])

#H2の座標
H2=np.array([x_array[0],y_array[0],0])
O=np.array([0.00,0.00,0.00])
H1=np.array([0.9693,0.00,0.00])

# 双極子モーメントベクトルの計算
polarization1=-2*(WF1+WF2+WF3+WF4)+6*O+(H1+H2)
print("polarization vector =", polarization1)

# 双極子モーメントの大きさの計算．現在の単位はAngstrom*1(e)となっている．
# 単位を合わせる．（単位がデバイになる．）
dipole1=np.linalg.norm(polarization1)*4.79990626955
print("dipole moment = ", dipole1, "  [D]" )

polarization vector = [ 3.59247179e-01  2.89648155e-01 -2.00000000e-06]
dipole moment =  2.215012892540141   [D]


In [70]:
# water_90
#WCの座標（単位はAngstrom）
WF1=np.array([-0.010585,  0.526317, -0.000000])
WF2=np.array([0.526317, -0.010585, -0.000000 ])
WF3=np.array([-0.092306, -0.092306,  0.283980 ])
WF4=np.array([-0.092306, -0.092306, -0.283980 ])

#H2の座標
H2=np.array([x_array[1],y_array[1], 0])

# 双極子モーメントベクトルの計算
polarization2=-2*(WF1+WF2+WF3+WF4)+6*O+(H1+H2)
print("polarization vector =", polarization2)

# 双極子モーメントの大きさの計算．現在の単位はAngstrom*1(e)となっている．
# 単位を合わせる．（単位がデバイになる．）
dipole2=np.linalg.norm(polarization2)*4.79990626955
print("dipole moment = ", dipole2, "  [D]" )

polarization vector = [0.30706 0.30706 0.     ]
dipole moment =  2.0843516967194695   [D]


In [71]:
# water_100
WF1=np.array([0.526634,  0.010402,  0.000022])
WF2=np.array([-0.078222,  0.520049,  0.000023 ])
WF3=np.array([-0.087862, -0.105571, -0.280392])
WF4=np.array([-0.087904, -0.105623,  0.280342 ])


#H2の座標
H2=np.array([x_array[2],y_array[2], 0])

# 双極子モーメントベクトルの計算
polarization3=-2*(WF1+WF2+WF3+WF4)+6*O+(H1+H2)
print("polarization vector =", polarization3)

# 双極子モーメントの大きさの計算．現在の単位はAngstrom*1(e)となっている．
# 単位を合わせる．（単位がデバイになる．）
dipole3=np.linalg.norm(polarization3)*4.79990626955
print("dipole moment = ", dipole3, "  [D]" )

polarization vector = [2.55690821e-01 3.16060155e-01 1.00000000e-05]
dipole moment =  1.9513364574925822   [D]


In [76]:
print(polarization2-polarization1)
print(delP)
print(delP2)

[-5.21871786e-02  1.74118450e-02  2.00000000e-06]


NameError: name 'delP' is not defined

In [75]:
#100度-80度
print(polarization3-polarization1)

[-1.03556357e-01  2.64120000e-02  1.20000000e-05]


# pol2のデータ（1度ずつ変化させたH2O）のBEC解析

- ASR補正
- 座標取得
- 双極子モーメント計算

In [73]:
# まず，座標のリストを取得する
z_list=np.zeros((3,21))
for i in range(80,101):
    z_list[0,i-80]=distance*np.cos(i*np.pi/180)
    z_list[1,i-80]=distance*np.sin(i*np.pi/180)

# ベクトルの取り出し方
print(z_list[:,0])

[0.16831718 0.95457415 0.        ]


In [78]:
print(distance*np.cos(100*np.pi/180))
print(distance*np.sin(100*np.pi/180))

-0.16831717861255555
0.9545741549947333


In [74]:
## 双極子モーメントの計算

# 初期化
pol=0

# ゼロベクトル
zero=np.zeros(3)

# 
for i in range(81,101):
    # 有効電荷の取得 
    ZO=np.loadtxt("./pol2/result2/bec_O_{}.txt".format(i))
    ZH1=np.loadtxt("./pol2/result2/bec_H1_{}.txt".format(i))
    ZH2=np.loadtxt("./pol2/result2/bec_H2_{}.txt".format(i))
    
    #  座標の差*BECで更新していく．（ASR適用すみ）
    pol+=polarization_BEC(ZO,ZH1,ZH2, zero, zero, z_list[:,i- 80]-z_list[:,i-81])

    print(i, pol)


81 [-5.06146137e-03  1.54455041e-03 -1.20542189e-07]
82 [-1.01494908e-02  3.02152088e-03 -2.40420226e-07]
83 [-1.52571576e-02  4.42930116e-03 -2.40420226e-07]
84 [-2.03859147e-02  5.76798602e-03 -2.34036598e-07]
85 [-2.55370624e-02  7.03589515e-03 -2.34036598e-07]
86 [-3.07074845e-02  8.23276285e-03 -2.34036598e-07]
87 [-3.58953299e-02  9.35720936e-03 -2.34036598e-07]
88 [-4.10995909e-02  1.04085894e-02 -2.34036598e-07]
89 [-4.63199247e-02  1.13855392e-02 -3.48255836e-07]
90 [-5.15534817e-02  1.22872214e-02 -4.61525383e-07]
91 [-5.68019298e-02  1.31129550e-02 -4.61525383e-07]
92 [-6.2063539e-02  1.3860922e-02 -5.7279234e-07]
93 [-6.73364535e-02  1.45304100e-02 -5.72792340e-07]
94 [-7.26177495e-02  1.51199920e-02 -6.81921143e-07]
95 [-7.79075770e-02  1.56288579e-02 -6.81921143e-07]
96 [-8.32078202e-02  1.60553211e-02 -6.81921143e-07]
97 [-8.85134520e-02  1.63987606e-02 -7.25182271e-07]
98 [-9.38215918e-02  1.66577585e-02 -7.25182271e-07]
99 [-9.91365028e-02  1.68307125e-02 -7.25182271e-

# 結果の解析

## BECによる方法
80-90：：[-5.15534817e-02  1.22872214e-02 -4.61525383e-07]
80-100：：[-1.04453906e-01  1.69168644e-02 -8.27110104e-07]

## wannierによる方法
80-90：：[-5.21871786e-02  1.74118450e-02  2.00000000e-06]
80-100：：[-1.03556357e-01  2.64120000e-02  1.20000000e-05]

[[-3.33900000e-02  7.40000000e-04  0.00000000e+00]
 [ 4.23333333e-04 -3.16233333e-02  0.00000000e+00]
 [ 6.66666667e-06  3.33333333e-06 -5.49466667e-02]]


# BECのK点メッシュ依存性h2o_polarization/bec_zue_asrたち

# ASRをちゃんと課すため，

# 水のMD計算の結果のBECを書き出す．

- 座標のリストはwork5/h2o_MD_座標計算と同じ方法で取得可能
- 座標の取得と双極子モーメントの計算は上の（ほぼ）コピペで行ける．

In [56]:
# まず，座標のリストを取得する
# ファイルを読み込み．
zahixyou=np.loadtxt("h2o_mol2.pos")
print(zahixyou)

[[ 9.90000000e-03  9.90000000e-03  0.00000000e+00]
 [ 1.82896845e+00 -2.24652669e-01  2.92522173e-03]
 [-2.23534394e-01  1.83033378e+00  6.98697185e-04]
 [ 9.90000000e-03  9.90000000e-03  0.00000000e+00]
 [ 1.82605464e+00 -2.24278426e-01  6.18214549e-03]
 [-2.22903058e-01  1.82714531e+00  1.12768217e-03]
 [ 9.90000000e-03  9.90000000e-03  0.00000000e+00]
 [ 1.83004965e+00 -2.23068650e-01  4.03081698e-03]
 [-2.22467650e-01  1.82646432e+00  1.54234565e-03]
 [ 9.90000000e-03  9.90000000e-03  0.00000000e+00]
 [ 1.82989765e+00 -2.22664084e-01  2.47327874e-03]
 [-2.21480217e-01  1.82556166e+00  1.55015138e-03]
 [ 9.90000000e-03  9.90000000e-03  0.00000000e+00]
 [ 1.82512200e+00 -2.22402873e-01  6.42737059e-03]
 [-2.20884316e-01  1.82414644e+00  1.01918162e-03]
 [ 9.90000000e-03  9.90000000e-03  0.00000000e+00]
 [ 1.82891419e+00 -2.22361645e-01  1.01984146e-02]
 [-2.21249473e-01  1.82797176e+00  2.29160718e-03]
 [ 9.90000000e-03  9.90000000e-03  0.00000000e+00]
 [ 1.83280292e+00 -2.22206815e-

In [89]:
test=np.array([[-0.46958,0.07461,-0.00005] ,
[0.07525,-0.43037,-0.00006],
[0.00000,0.00000,-0.68518]] )

eig = np.linalg.eig(test)
print(eig)

(array([-0.52742665, -0.37252335, -0.68518   ]), array([[-7.90292447e-01, -6.09459451e-01,  1.67547820e-04],
       [ 6.12729833e-01, -7.92817241e-01,  1.85989658e-04],
       [ 0.00000000e+00,  0.00000000e+00,  9.99999969e-01]]))


In [86]:
## 双極子モーメントの計算

# polの保存．
pol_list=np.zeros([30,3])

# 初期化
pol=0

# range(a,b)はaからb-1まで．
# BECの場合は一つ減らしておく．
for i in range(0,29):
    # 有効電荷の取得 
    ZO=np.loadtxt("./pol2/result_bec/bec_O_{}.txt".format(i))
    ZH1=np.loadtxt("./pol2/result_bec/bec_H1_{}.txt".format(i))
    ZH2=np.loadtxt("./pol2/result_bec/bec_H2_{}.txt".format(i))
    
    #  座標の差*BECで更新していく．
    pol+=polarization_BEC(ZO,ZH1, ZH2, zahixyou[3*i+3]-zahixyou[3*i], zahixyou[3*i+4]-zahixyou[3*i+1], zahixyou[3*i+5]-zahixyou[3*i+2])
    #pol+=polarization_BEC(ZO,ZH1, ZH2, zahixyou[3*i]-zahixyou[3*i-3], zahixyou[3*i+1]-zahixyou[3*i-2], zahixyou[3*i+2]-zahixyou[3*i-1])

    pol_list[i]=pol
    print(i+1,np.linalg.norm(pol)*4.79990626955)


1 0.0027088744790604597
2 0.0033410674937740005
3 0.003625918724382977
4 0.0042063138606599874
5 0.007184045113053354
6 0.00713586094834175
7 0.0059967804938986305
8 0.007776724740649328
9 0.011129521947752763
10 0.010336379846641014
11 0.007461439516532239
12 0.008652430700936483
13 0.010630795535142797
14 0.009092774214849017
15 0.006555090532945946
16 0.006386787752972825
17 0.009111907544440216
18 0.007797632802766031
19 0.003314187956901651
20 0.005354214656870301
21 0.008782593453809254
22 0.00650378399180497
23 0.005825967459103531
24 0.00903901374573332
25 0.009289613635667122
26 0.007942977257072896
27 0.008616526978962058
28 0.008875129954456263
29 0.008753341845314783


# 水のMD計算の結果のwannierを書き出す．

- 座標のリストはwork5/h2o_MD_座標計算と同じ方法で取得可能→ 上のを流用する．
- 座標の取得と双極子モーメントの計算は上の（ほぼ）コピペで行ける．

In [84]:
#polデータの配列

# polの保存．
pol_wan_list=np.zeros([30,3])

# range(a,b)はaからb-1まで．
for i in range(0,30):
    
    #O，Hの座標
    O=zahixyou[3*i]
    H1=zahixyou[3*i+1]
    H2=zahixyou[3*i+2]

    #ファイルから読み込み
    WCs=np.loadtxt("./pol2/result_wan/wan2_{}.txt".format(i))
    
    # 4つのWannierCenterの取得 
    WC1=WCs[0]
    WC2=WCs[1]
    WC3=WCs[2]
    WC4=WCs[3]

    # 双極子モーメントを計算
    pol_wan= polarization_WF(WC1,WC2,WC3,WC4,O,H1,H2)
    print(i, pol_wan)
    pol_wan_list[i]=pol_wan
    #print(i, pol_wan)


print("#######################")
print("# pol[0]との差を計算")
for i in range(0,30):
    print(i, np.linalg.norm(pol_wan_list[i]-pol_wan_list[0])*4.79990626955)

0 [0.34523006 0.34515111 0.00084792]
1 [0.34447358 0.34434088 0.00171183]
2 [0.345112   0.34466367 0.00130316]
3 [0.34523944 0.34456158 0.00093743]
4 [0.34450969 0.34428957 0.00174255]
5 [0.34534072 0.34501012 0.00291802]
6 [0.34581982 0.3454982  0.00283073]
7 [0.34545894 0.34540864 0.00229134]
8 [0.34527246 0.34520789 0.00306545]
9 [0.34590665 0.34534073 0.00421369]
10 [0.3458262  0.34495261 0.00383597]
11 [0.34509628 0.34412869 0.00279779]
12 [0.34549433 0.34405522 0.00345348]
13 [0.34555821 0.34450241 0.00412881]
14 [0.35177937 0.38870476 0.0033442 ]
15 [0.34529075 0.3446288  0.00259686]
16 [0.34548334 0.34452659 0.00264555]
17 [0.34535211 0.34438464 0.00338938]
18 [0.34513491 0.34383294 0.00293417]
19 [0.3452887  0.34364088 0.00162659]
20 [0.34528658 0.34356297 0.0020897 ]
21 [0.34524885 0.34372153 0.00296455]
22 [0.34552913 0.34412669 0.0023584 ]
23 [0.3457622  0.34437098 0.00164462]
24 [0.34623972 0.344659   0.00206989]
25 [0.34602788 0.34462312 0.00280331]
26 [0.34616549 0.34423

# BECとwannierの結果の比較．

In [95]:
WF1=np.array([-0.316204, -0.000219, -0.004067])
WF2=np.array([ 0.447678,  0.076490,  0.048498])
WF3=np.array([1.531495,  0.000154,  0.000834])
WF4=np.array([0.307460, -0.095170, -0.020987 ])
WF5=np.array([0.295652,  0.009381, -0.027709])

C=np.array([1.14, 0, 0])
O=np.array([0, 0, 0])

polarization=-2*(WF1+WF2+WF3+WF4+WF5)+6*O+4*C
print(polarization)
d_test=np.linalg.norm(polarization)*4.79990626955
print(d_test)

[0.027838 0.018728 0.006862]
0.16437694228797617


実験値は0.112 Dらしいので，なんか全然会ってないね．

In [101]:
ZO=np.array(
[[0.63364,        0.00000 ,      -0.00000],
 [0.00000 ,       -0.01822  ,     -0.00000],
 [0.00000  ,      0.00000   ,     -0.01821]]
)

ZC=np.array(
[[-0.63364 ,      -0.00000   ,     0.00000],
 [-0.00000  ,      0.01822     ,    0.00000],
 [-0.00000   ,    -0.00000     ,  0.01821]]
)

P=np.dot(ZO,O)+np.dot(ZC,C)
print(P)
print(np.linalg.norm(P)*4.79990626955)

[-0.7223496  0.         0.       ]
3.4672103738469344


In [97]:
print(1.14*0.01821)

0.020759399999999997


In [102]:
polarization=O-C
print(polarization)
d_test=np.linalg.norm(polarization)*4.79990626955
print(d_test)

[-1.14  0.    0.  ]
5.471893147287
